import React from "react";
import { MainWrapper } from "../../components/main/main.styled";

const Main = () => {
  return (
    <MainWrapper>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
      <div>Main</div>
    </MainWrapper>
  );
};

export default Main;
